spring:
  application:
    name: day04
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hmdp?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 200369

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.day04.entity
  configuration:
    map-underscore-to-camel-case: true